#!/bin/sh

cp -r ./Config ./zfp/Config
cp -r ./src/Makefile ./zfp/src/Makefile
cp -r ./src/zfp_wasm.c ./zfp/src/zfp_wasm.c

pushd ./zfp
make clean
emmake make
emcc \
    -O3 \
    -s MODULARIZE='1' \
    -s EXPORT_NAME='"ZfpModule"' \
    -s EXPORTED_FUNCTIONS=_malloc,_free \
    -s EXPORTED_RUNTIME_METHODS='["ccall"]' \
    lib/libzfp.so -o zfp_wasm.js
mv ./zfp_wasm.{js,wasm} ..
popd
